config/routes.rb
Rails.application.routes.draw do
  resources :pokemons
  get 'pokemons/:id/new_evolution' => 'pokemons#new_evolution', as: :evolve_pokemon

end

app/models/move.rb
class Move < ActiveRecord::Base
	belongs_to :type

	has_many :pokemon_moves
	has_many :pokemons, :through => :pokemon_moves
end

app/models/pokemon.rb
class Pokemon < ActiveRecord::Base
	########################################
	# Associations
	########################################
	belongs_to :type
	belongs_to :evolves_from, class_name: "Pokemon"
    
    has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "32x32>" }, :default_url => "/images/:style/missing.png"

	has_many :pokemon_moves, :dependent => :destroy
	has_many :moves, :through => :pokemon_moves
	accepts_nested_attributes_for :pokemon_moves, :reject_if => lambda { |m| m[:move_id].blank?}, :allow_destroy => true

	has_many :weaknesses, :dependent => :destroy
	accepts_nested_attributes_for :weaknesses, :reject_if => lambda { |w| w[:type_id].blank?}, :allow_destroy => true
	########################################
	# Validations
	########################################
	validates :name, presence: true
	validates :name, uniqueness: true
	validates :type, presence: true
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	########################################
	# Methods
	########################################
	def build_associations
		build_moves
		build_weaknesses
	end

	def build_moves
	  if pokemon_moves.count == 0
	  	4.times { pokemon_moves.build }
	  elsif pokemon_moves.count < 4
	  	pokemon_moves.build
	  end
	end

	def build_weaknesses
	  weaknesses.build
	end
end

app/models/pokemon_move.rb
class PokemonMove < ActiveRecord::Base
	########################################
	# Associations
	########################################
	belongs_to :pokemon
	belongs_to :move
	########################################
	# Validations
	########################################
	validates_uniqueness_of :move_id, :scope => :pokemon_id
end

app/models/type.rb
class Type < ActiveRecord::Base
	has_many :moves
	has_many :pokemons

	has_many :weaknesses
end

app/models/weakness.rb
class Weakness < ActiveRecord::Base
	belongs_to :pokemon
	belongs_to :type
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: [:show, :edit, :update, :destroy]

  # GET /pokemons
  # GET /pokemons.json
  def index
    @pokemons = Pokemon.all
    # this is for testing
    # binding.pry
  end

  # GET /pokemons/1
  # GET /pokemons/1.json
  def show
  end

  # GET /pokemons/new
  def new
    @pokemon = Pokemon.new
    @pokemon.build_associations
  end

  # GET /pokemons/1/new_evolution
  def new_evolution
    @pokemon = Pokemon.find(params[:id]).dup
    @pokemon.id = nil
    @pokemon.build_associations
  end

  # GET /pokemons/1/edit
  def edit
    @pokemon.build_associations
  end

  # POST /pokemons
  # POST /pokemons.json
  def create
    @pokemon = Pokemon.new(pokemon_params)

    respond_to do |format|
      if @pokemon.save
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully created.' }
        format.json { render :show, status: :created, location: @pokemon }
      else
        @pokemon.build_associations
        format.html { render :new }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemons/1
  # PATCH/PUT /pokemons/1.json
  def update
    respond_to do |format|
      if @pokemon.update(pokemon_params)
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully updated.' }
        format.json { render :show, status: :ok, location: @pokemon }
      else
        format.html { render :edit }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemons/1
  # DELETE /pokemons/1.json
  def destroy
    @pokemon.destroy
    respond_to do |format|
      format.html { redirect_to pokemons_url, notice: 'Pokemon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pokemon_params
      params.require(:pokemon).permit(:name, :type_id, :image, :evolves_from_id, \
        pokemon_moves_attributes: [:id, :move_id, :_destroy], \
        weaknesses_attributes: [:id, :type_id, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DevcampPokedex</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pokemons/_form.html.erb
<%= form_for(@pokemon) do |f| %>
  <% if @pokemon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pokemon.errors.count, "error") %> prohibited this pokemon from being saved:</h2>

      <ul>
      <% @pokemon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if params[:id] and not @pokemon.id %>
    <div class="field">
      <%= hidden_field_tag("pokemon[evolves_from_id]", params[:id]) %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name, "Name*" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type_id, "Type*" %><br>
    <%= f.collection_select(:type_id, Type.all, :id, :name, prompt: true) %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="moves">
    <%= label_tag "Moves" %><br>
    <ol>
    <%= f.fields_for :pokemon_moves do |m| %>
      <%= render "move_fields", builder: m %>
    <% end %>
    </ol>
  </div>
  <div class="weaknesses">
    <%= label_tag "Weaknesses" %><br>
    <ul>
    <%= f.fields_for :weaknesses do |w| %>
      <%= render "weakness_fields", builder: w %>
    <% end %>
    </ul>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <div class="note">
    <p><small>Fields with an asterisk (*) are required.</small></p>
  </div>
<% end %>

app/views/pokemons/_move_fields.html.erb
<li class="fields">
  <%= builder.collection_select(:move_id, Move.all, :id, :name, prompt: true) %>
</li>

app/views/pokemons/_weakness_fields.html.erb
<li class="fields">
  <%= builder.collection_select(:type_id, Type.all, :id, :name, prompt: true) %>
</li>

app/views/pokemons/edit.html.erb
<h1>Editing Pokemon</h1>

<%= render 'form' %>

<%= link_to 'Show', @pokemon %> |
<%= link_to 'Back', pokemons_path %>

app/views/pokemons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pokemon</h1>

<table>
  <thead>
    <tr>
      <th colspan="1"></th>
      <th>Name</th>
      <th>Type</th>
      <th colspan="4">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @pokemons.each do |pokemon| %>
      <tr>
        <td>
          <% if pokemon.image %>
           <%= image_tag pokemon.image.url(:thumb) %>
          <% end %>
        </td>
        <td><%= pokemon.name %></td>
        <td><%= pokemon.type.name %></td>
        <td><%= link_to 'Show', pokemon %></td>
        <td><%= link_to 'Edit', edit_pokemon_path(pokemon) %></td>
        <td><%= link_to 'Evolve', evolve_pokemon_path(pokemon) %></td>
        <td><%= link_to 'Destroy', pokemon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pokemon', new_pokemon_path %>

app/views/pokemons/new.html.erb
<h1>New Pokemon</h1>

<%= render 'form' %>

<%= link_to 'Back', pokemons_path %>

app/views/pokemons/new_evolution.erb
<h1>Editing Pokemon</h1>

<%= render 'form' %>

<%= link_to 'Show Prior', Pokemon.find(params[:id]) %> |
<%= link_to 'Back', pokemons_path %>

app/views/pokemons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pokemon.name %>
</p>

<% if @pokemon.evolves_from %>
  <strong>Evolves From:</strong><br>
  <%= @pokemon.evolves_from.name %>
<% end %>

<p>
  <strong>Type:</strong>
  <%= @pokemon.type.name %>
</p>

<% if @pokemon.image %>
  <strong>Image:</strong><br>
  <%= image_tag @pokemon.image.url(:medium) %>
<% end %>


<% if @pokemon.moves.count > 0 %>
  <p><strong>Moves:</strong></p>
  <ol>
  <% @pokemon.moves.each do |move| %>
    <li><%= move.name %></li>
  <% end %>
  </ol>
<% end %>

<p><strong>Weaknesses:</strong>
<% if @pokemon.weaknesses.count > 0 %>
  </p>
  <ul>
  <% @pokemon.weaknesses.each do |weakness| %>
    <li><%= weakness.type.name %></li>
  <% end %>
  </ul>
<% else %>
  <br>None</p>
<% end %>

<%= link_to 'Edit', edit_pokemon_path(@pokemon) %> |
<% if @pokemon.evolves_from %>
<%= link_to 'Show Prior', @pokemon.evolves_from %> |
<% end %>
<%= link_to 'Add Evolution', evolve_pokemon_path(@pokemon) %> |
<%= link_to 'Back', pokemons_path %>